language: ruby
dist: xenial
sudo: required
addons:
  chrome: stable
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
  - vendor/bundle
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
- bundle install --deployment
- nvm install
- node --version
- yarn install
before_script:
- export SECRET_KEY_BASE=`bundle exec rake secret`
- bundle exec rake db:create RAILS_ENV=test
- RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update -r webdrivers
- ln -s /home/travis/.webdrivers/chromedriver ~/bin/chromedriver
- export PATH=~/bin:$PATH
script:
- bundle exec rspec
- xvfb-run -a bundle exec rspec --tag browser
- yarn test
after_success:
- chmod +x ./compile-build
- "./compile-build"
services:
- redis-server
- mysql
- xvfb
deploy:
  provider: releases
  api_key:
    secure: KO46Zxg55+qAiURnkgbu5p5TzFC4rYzgJ4KLqvW4h8c8JKZWgGVAHT6mAgKwuI3Kgzg2PR1M94FCch1DiH7/Y3mMRemWfB0Vy4lP9HE0O9R/Cz7zlBU1W8fgfiQ4qP+h4WurJp7sUEXCupApSZrAEAumUNL80XlQbD1XvCy9pzfz1w2Pt7gvcqTMM+pS/20icjz8VXUz9AGDwDFpKNyfP+kmQPJUKTJ6tJ44X/A3+VfoEjcHub5/egsLKt0h15JPGiR/hLpZDaH/x5f+zeeiHkL+EqduyqzsVHDVlY9zDTeQKmB1LZ3eH0xmTZwwB7pryZT1ldXodwU7Wt2uwwo6nrmAhVPbsS5cQ2TWCNOh2EbO+F1szF0glO5L1TVCK80P4VA0wOG4SrzeURoXPK6bi4SuynCoYJPzzy1KCpfKCdZAH1MtqhQ20oTq4y8KFs/9Q8BEZxNacu4nmyW4UlwYVgDaPdg+l2mDlR79/pKo3pVf6ZxKHBNKJukU4LhQMiVho2eym+ExC274E8PlXXdosgexieUUStFBLaF5i037nQa6YBJPjkS0DAiQs35o7fAanZjIVGkITH9NHGr5/Hh7Sv5q6SKBo1M+GS/nCp0Xu5BAIYizupczcNhqHGYZNmS2B4/zV+vJ5qvDsIInODKSEArMxdC2Y0+k0KxhtlERLhc=
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: sanger/samples_extraction
    tags: true
