language: ruby
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
  - vendor/bundle
install:
- bundle install --deployment
- yarn install
before_script:
- export SECRET_KEY_BASE=`bundle exec rake secret`
- bundle exec rake db:create RAILS_ENV=test
script:
- bundle exec rake
- yarn test
after_success:
  - chmod +x ./compile-build
  - "./compile-build"
services:
- redis-server
- mysql

