language: ruby
cache: bundler
before_script:
  - "export SECRET_KEY_BASE=`bundle exec rake secret`"
  - "bundle exec rake db:create RAILS_ENV=test"
script:
  - bundle exec rake
  - yarn test
services:
  - redis-server
  - mysql
