language: ruby
dist: xenial
sudo: required
services: mysql
bundle_args: "--without deployment"
cache:
  bundler: true
before_script:
- bundle exec rake db:create
script:
- bundle exec rspec
before_deploy: "./compile-build"
deploy:
  provider: releases
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: sanger/samples_extraction
  api_key:
    secure: FmlBKcMUoYu3WabeR6CdtSn/QJqoJ/sYnfaIGOSLiHlbGiQiFEzzC20A5KTswp2SiDkDym7e/l9XwA/DHmPrwuusL5TgXHVzBm9/fxK6YERlv8Ys74GcEuzGcpNazPdDN/hZBnenXJ+zo+D0gnL8n2qwlPEngAUgv9lG0OChlCfdH0snKfvRiTNppkX3db1MUHbr91IqdMluDY0mmaIs14hPRGVemjuHBjdlCmlFf17wvGeG3Rs88vNdVtXkxRmPutOwNiBABAxRpQIZh29G2IVPEq4fitOzSdnVGML+IjA1iF3r45sVDI1Kcg1TPa0TzwTw5EgUlm0yNtbFXzOqjAOEsziEwYXekZItusroHfxW2O3G7ER8j0lmb4ycmki6rFxclOAVmJDe5g0LAmoVSyMx+wipW9CyrmkbenpaAr1jRjMGSrj6Ra0/5NGsUWx0MOWoPxkjniH+t2btKMXj4ZL0he1uzXVuhBTm2HOWVEQiv+QgpeDIHyh23DpDCAWX/XjtNbkWC+0OwbuPPodIwgw0Q+2GsTJvQdkQrOxGQiHQIjeqnH2kRajxFXn0rCpLGQu3I9Ag9zrfpGHvM9q4Kcmgd83txbF8AcqKk4LtEFM0bJfySb2O9soId5/d6NuHgoIXg0A5m5yAucdzA6iGoA1lIP6J+6vwn+wY3uJ6Zu4=
