name: Build and publish Docker image
on:
  push:
    branches:
      - develop
      - master
      - test-github-actions

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_and_publish:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_DATABASE: samples_extraction_test
          MYSQL_ROOT_PASSWORD:
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - run: env
    - uses: actions/checkout@v1
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
    - name: Tag (latest) the Docker image
      run: docker tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} docker.pkg.github.com/${IMAGE_NAME}:latest
      if: github.ref == 'refs/heads/master'
    - name: Run Rspec tests against the image
      run: docker run docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} bundle exec rspec
    - name: Run JS tests against the image
      run: docker run docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} yarn test

    - name: Login to regitry
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Publish image
      run: docker push docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
    - name: Publish image (latest)
      run: docker push docker.pkg.github.com/${IMAGE_NAME}:latest
      if: github.ref == 'refs/heads/master'
